/* AUTH TYPES */
export const SET_LOGIN_SUCCESS = "SET_LOGIN_SUCCESS";
export const SET_LOGIN_FAIL = "SET_LOGIN_FAIL";
export const SET_USER_LOADED = "SET_USER_LOADED";
export const SET_AUTH_ERROR = "SET_AUTH_ERROR";
export const SET_AUTH_LOADING = "SET_AUTH_LOADING";
export const SET_TOKEN = "SET_TOKEN";
export const SET_REFRESH_TOKEN = "SET_REFRESH_TOKEN";
export const SET_LOGOUT_AT = "SET_LOGOUT_AT";
export const SET_IS_AUTHENTICATED = "SET_IS_AUTHENTICATED";

/* PROFILE TYPES */
export const SET_PROFILE = "SET_PROFILE";
export const SET_PROFILE_ERROR = "PROFILE_ERROR";
export const CLEAR_PROFILE = "CLEAR_PROFILE";
export const UPDATE_PROFILE = "UPDATE_PROFILE";
export const SET_ACTIVE = "SET_ACTIVE";
export const SET_ASSIGNED_TASK = "SET_ASSIGNED_TASK";
export const SET_COMPLETED_TASK = "SET_COMPLETED_TASK";
export const SET_PENDING_TASK = "SET_PENDING_TASK";


/* ADMIN TYPES */
export const SET_TASKS = "SET_TASKS"
export const SET_USERS = "SET_USERS"